name: 'Checkwise'
description: 'Generate dynamic Pull Request checklists based on changed file paths using declarative YAML configuration'
author: 'inciarmors'
inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
    default: ${{ github.token }}
  config-path:
    description: 'Path to YAML configuration file'
    required: false
    default: '.github/checkwise.yml'
runs:
  using: 'node20'
  main: 'dist/main.js'
branding:
  icon: 'check-square'
  color: 'blue'