name: Bug Report
description: File a bug report to help us improve Checkwise
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! This helps us improve Checkwise for everyone.
        
        Please search existing issues before creating a new one to avoid duplicates.

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: "checkwise@proton.me"
    validations:
      required: false

  - type: dropdown
    id: version
    attributes:
      label: Checkwise Version
      description: What version of Checkwise are you using?
      options:
        - v1.0.0
        - main branch
        - other (specify in description)
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: |
        Describe the bug clearly and what you expected to happen instead.
        Include any error messages you're seeing.
      placeholder: |
        1. I configured Checkwise with...
        2. When I opened a PR that modified...
        3. I expected to see...
        4. But instead I saw...
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration File
      description: Please paste your Checkwise configuration (`.github/checkwise.yml`)
      render: yaml
      placeholder: |
        checklists:
          - when: ["src/**/*.ts"]
            require: ["Tests added"]
    validations:
      required: true

  - type: textarea
    id: workflow
    attributes:
      label: Workflow Configuration
      description: Please paste your GitHub workflow that uses Checkwise
      render: yaml
      placeholder: |
        name: Checkwise
        on:
          pull_request:
            types: [opened, synchronize]
        jobs:
          checkwise:
            runs-on: ubuntu-latest
            steps:
              - uses: actions/checkout@v4
              - uses: inciarmors/checkwise@v1
                with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Action Logs
      description: |
        Please copy and paste relevant log output from the GitHub Action.
        You can find this in the "Actions" tab of your repository.
      render: shell
      placeholder: |
        Run inciarmors/checkwise@v1
        Error: Configuration file not found...
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Tell us about your environment
      value: |
        - Repository type: (public/private/enterprise)
        - GitHub plan: (free/pro/team/enterprise)
        - Runner: (ubuntu-latest/self-hosted/other)
        - Files changed in PR: (approximate number)
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
