# Example of INVALID configuration - demonstrates validation errors

# ERROR: Missing required "checklists" property
# Should be:
# checklists:
#   - when: ["src/**"]
#     require: ["Tests"]

# ERROR: checklists is not an array
checklists: "this should be an array"

# ERROR: Empty checklists array
# checklists: []

# ERROR: Invalid rule structure
# checklists:
#   - "this should be an object"

# ERROR: Missing "when" property
# checklists:
#   - require: ["Tests"]

# ERROR: "when" is not an array
# checklists:
#   - when: "should be an array"
#     require: ["Tests"]

# ERROR: Empty "when" array
# checklists:
#   - when: []
#     require: ["Tests"]

# ERROR: Non-string pattern in "when"
# checklists:
#   - when: ["valid", 123]
#     require: ["Tests"]

# ERROR: Empty pattern in "when"
# checklists:
#   - when: ["valid", "  "]
#     require: ["Tests"]

# ERROR: Missing "require" property
# checklists:
#   - when: ["src/**"]

# ERROR: "require" is not an array
# checklists:
#   - when: ["src/**"]
#     require: "should be an array"

# ERROR: Empty "require" array
# checklists:
#   - when: ["src/**"]
#     require: []

# ERROR: Non-string item in "require"
# checklists:
#   - when: ["src/**"]
#     require: ["Valid", 123]

# ERROR: Empty item in "require"
# checklists:
#   - when: ["src/**"]
#     require: ["Valid", "   "]

# ERROR: Invalid "optional" type
# checklists:
#   - when: ["src/**"]
#     require: ["Tests"]
#     optional: "should be boolean"

# ERROR: Invalid "options" type
# options: "should be an object"

# ERROR: Invalid "label_filter" type
# options:
#   label_filter: "should be an array"

# ERROR: Invalid label in "label_filter"
# options:
#   label_filter: ["valid", 123]

# ERROR: Invalid "branch_pattern" type
# options:
#   branch_pattern: 123

# ERROR: Invalid "comment_header" type
# options:
#   comment_header: 123
